### ISSUE TITLE
Emergency procedure in case of fire is not correct

### ISSUE THREAD

**Issue by esavary** [TheAxonLab/hcph-sops#148]
In case of a fire, we should not attempt rolling the bed out of the room unless the participant cannot walk (I may be wrong, but I do not recall this specific instruction being mentioned in our security training). We could maybe refer only to the initial step of the manual extraction procedure in this scenario to make it more clear.

**Comment by celprov** [comment]
The reasoning is that in case of fire, you have to shut down electricity and as a consequence you cannot take the bed out of the bore electrically, you have to do it manually. So 1. there is no "if the bed is stuck inside the bore" it will definitely be  (in electrical sense) because there would be no electricity. 2. To take the participant, you have to proceed with the manual extraction.
