### ISSUE TITLE
Keeping track of sessions notes

### ISSUE THREAD

**Issue by celprov** [TheAxonLab/hcph-sops#173]
I agree with @bfranceschiello that taking notes about sessions should be easy.
With that goal in mind, I think the spreadsheet is suitable.

Feel free to debate other options here.

If the team agrees, then we need to prepare the barebone of this spreadsheet.

**Comment by acionca** [comment]
Do you think we could make use of the `_scan.tsv` files (see [here](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#scans-file)) and `_session.tsv` files (see [here](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#sessions-file)) from the BIDS specification ?

Let's say we have `_scan.tsv` templates ready to be filled for each session, then, if there's an issue, the operator can add a comment for the specific scan that went wrong. Then we may report any unusual stuff in the `_session.tsv` to have an overview. For sure it will be a bit more work than a single spreadsheet but maybe it's worth to make it standardized.

**Comment by oesteban** [comment]
I think these are two different things @acionca. It is not completely unrelated because some of the information recorded with the session notes will probably need be included in the `_scan.tsv` and `_session.tsv` files.

To me, the choice is as follows: should we just start some Google Spreadsheets for this and share the links (as secrets) through the SOPs, or we spend time in improving the SOPs and add Javascript behavior to collect more data and allow including comments?

Option 1 can be implemented today. Option 2 is very unclear, it probably involves a lot of debugging and we may suffer from some scares (a session's worth of data lost because of a bug).

**Comment by celprov** [comment]
@oesteban I would go with Option1. We already have a lot on our plate, let's keep it simple. The second advantage of spreadsheet is that everyone is familiar with them.

One element I was worried about spreadsheet: What if someone accidentally erases comments for a previous session?
To avoid this mistake, I suggest we should [lock cells](https://blog.hubspot.com/marketing/how-to-lock-cells-in-google-sheets) when we finish a session.

Then, to bridge with your comment @acionca, David Kennedy from the ReproNim team suggested that once you have the spreadsheet you can automatize the recording of that information into the BIDS dataset using ReproSchema. That's a lead we can maybe investigate.

**Comment by celprov** [comment]
The CNeuroMod team have a [nice scanning issues template](https://github.com/courtois-neuromod/bids_template/blob/main/.github/ISSUE_TEMPLATE/scan-session.yml). I think we should also prepare a checklist of possible issues in our spreadsheet.
