### ISSUE TITLE
[Protocol] Final "cleanup"

### ISSUE THREAD

**Issue by oesteban** [TheAxonLab/hcph-sops#181]
Consolidate the protocol with the different PE variants

cc/ @helenelajous 

EDIT: annotating here all related issues

- [x] #176
- [x] #179
- [x] #180
- [x] #192
- [x] #193
- [x] #194
- [x] #195
- [x] #196
- [x] #197
- [x] #198
- [x] #200
- [x] #217

**Comment by oesteban** [comment]
This also involves #176, #179 and #180. There were also some suggestions from @helenelajous - can you write them down here, Helene?

(assigning this one to you, feel free to remove yourself if you feel you don't have time to finish this one).

**Comment by helenelajous** [comment]
Here are some suggestions for minor changes to the protocol, or at least things to check/be aware of:

- DWI: ensure 3D isotropic volumes
The exported protocol indicates 1.6 x 1.6 x 1.6 mm3, but there is a small discrepancy between the in-plane spatial resolution (FoV Read, 228 mm; base resolution, 146 voxels) and the slice thickness (1.6 mm).

- fMRI:
-- fmap_epi: we should double-check the TR/TE of the field map => The TR is highly different (much longer) from the TR of the functional acquisitions; is that okay? Was that on purpose?
-- rs: ensure that the movie starts well at the end of the dummy scans => It started a little beforehand on July 14th 2023.
-- bht: ensure the recordings start on time (started at 8/207 on July 14th 2023).

- Adjustments related to the PE direction: Importantly, we should check/change the gradient rise time depending on the PE direction to avoid warning messages from the scanner which will prevent us from acquiring the data (issue with the field map in the RL PE direction on July 14th 2023) => Ideally, we should check the different PE variants during the next session to be able to run the whole protocol in the different configurations and prevent any discrepancy in the acquisitions from one session to the other, but also depending on the operator, so that we keep consistent between sessions/operators.

**Comment by helenelajous** [comment]
Happy to discuss and have a look at the scanner next week!

**Comment by oesteban** [comment]
> * DWI: ensure 3D isotropic volumes

Sounds good, thanks for looking into this.



> * The TR is highly different (much longer) from the TR of the functional acquisitions; is that okay? Was that on purpose?

Yes, this is intended. The idea is that  BOLD has better contrast and much less noise. Now that you mention this, one thing where we would be very innovative is that the resolution of these EPIs is made higher so that we have a better measurement of the field. If we would nearly match that of the T2w, then this would be incredibly useful.



> * ensure that the movie starts well at the end of the dummy scans => It started a little beforehand on July 14th 2023.

This is weird. was it manually triggered @esavary ?



> * bht: ensure the recordings start on time (started at 8/207 on July 14th 2023).

Ditto - was this manually triggered?

> * Adjustments related to the PE direction: Importantly, we should check/change the gradient rise time depending on the PE direction to avoid warning messages from the scanner which will prevent us from acquiring the data (issue with the field map in the RL PE direction on July 14th 2023) => Ideally, we should check the different PE variants during the next session to be able to run the whole protocol in the different configurations and prevent any discrepancy in the acquisitions from one session to the other, but also depending on the operator, so that we keep consistent between sessions/operators.

Totally agreed.

**Comment by esavary** [comment]
No, we only manually triggered the movie during the DWI. At the beginning of the first functional task, I noticed the USB cable plugged in was wrong because the psychopy task didn't start. So, I plugged the right one, and then we restarted the sequence. After that, the scanner triggered the tasks as usual.

**Comment by helenelajous** [comment]
> One thing where we would be very innovative is that the resolution of these EPIs is made higher so that we have a better measurement of the field. If we would nearly match that of the T2w, then this would be incredibly useful.

This will come at the cost of a longer acquisition time, but let's see what we can do about it :)

**Comment by oesteban** [comment]
> > One thing where we would be very innovative is that the resolution of these EPIs is made higher so that we have a better measurement of the field. If we would nearly match that of the T2w, then this would be incredibly useful.
> 
> This will come at the cost of a longer acquisition time, but let's see what we can do about it :)

I'm aware - but it's totally worth it.

**Comment by oesteban** [comment]
> No, we only manually triggered the movie during the DWI. At the beginning of the first functional task, I noticed the USB cable plugged in was wrong because the psychopy task didn't start. So, I plugged the right one, and then we restarted the sequence. After that, the scanner triggered the tasks as usual.

If this is the case, we'll need to make sure if these delays are also present in the previous sessions. If not, we can breathe normally and interpret that the missing cable did have a role in introducing these delays. Otherwise, this is looking like a big problem.

**Comment by helenelajous** [comment]
> > > One thing where we would be very innovative is that the resolution of these EPIs is made higher so that we have a better measurement of the field. If we would nearly match that of the T2w, then this would be incredibly useful.
> > 
> > 
> > This will come at the cost of a longer acquisition time, but let's see what we can do about it :)
> 
> I'm aware - but it's totally worth it.

Which duration would be acceptable @oesteban?
Do we want to acquire field maps in the 4 PE directions in the final protocol?

**Comment by oesteban** [comment]
> Which duration would be acceptable @oesteban?

Anything within, say, 2 min?



> Do we want to acquire field maps in the 4 PE directions in the final protocol?

No, we don't *in principle*. In the final protocols (there'll be 4 of them: AP, PA, LR, RL), we will have the two opposing directions. What those should be is less clear to me. While standard practice would say acquiring them in the same PE direction (e.g., protocol es PA then we would acquire two EPI fieldmaps -> AP & PA), it would be interesting to acquired orthogonal PE directions (e.g., protocol is PA and we get LR and RL).

I'm inclined to do the latter (orthogonal), or else the 4 of them always and dump my *in principle* above.

**Comment by oesteban** [comment]
@helenelajous' notes from Friday 22.09.2023:

> 3. 75%
> 4. 90%
> 5. 100% + strict transversal
> 6. Cor - 90.6%
> 7. T2-SPACE Ax. L>>R
> 8. Comment
> 9. T2-SPACE Ax. A>>P

I believe these correspond to the T1w and T2w images we acquired (in BIDS - `ses-pilot017`).

**Comment by helenelajous** [comment]
The percentages reported for the scans 3. to 6. correspond to the FOV phase we tested on the MPRAGE (in those cases, always with wrap-around artifacts).
Scans 3. and 4. were acquired with autoalign "Head > Basis" (vs. strict orientation for scans 5. and 6.).

**Comment by oesteban** [comment]
All items checked. Closing!
