### ISSUE TITLE
Description of how to start a New Examination is completely missing

### ISSUE THREAD

**Issue by oesteban** [TheAxonLab/hcph-sops#200]
After converting to BIDS, the `_scans.tsv` file of each session has other people's names in the column "operator". This information is stored in the DICOM files, so we want to set it properly before every session.

EDIT:

The problem above led to identify that we do not have any screenshot of this menu nor details in the SOPs:
- [x] Write this section
- [x] Make sure we set the OPERATOR field

**Comment by helenelajous** [comment]
Indeed, I told you when we started scanning, but at that time the idea was to have always the same person running the session, so it didn't seem relevant. About this, the operator will have to take care of filling the different fields **sequentially**, otherwise it becomes impossible to fill the "operator" field. I'll show you later!

**Comment by oesteban** [comment]
I was checking the SOPs and we don't have anything about what happens when you start a New Examination. I'm changing the title.
