### ISSUE TITLE
Get blood sample before and after

### ISSUE THREAD

**Issue by celprov** [TheAxonLab/hcph-sops#225]
Pierre Bellec suggested the idea of collecting a blood sample before and after in order to check for chromosomal damage.
Even if we don't find anyone who can perform this test by the time the data collection starts, Pierre said it is possible to store the blood sample while finding someone.

**Comment by helenelajous** [comment]
In their paper "The effects of repeated brain MRI on chromosomal damage" (European Radiology Experimental, 2022), Herate et al. explore the integrity of DNA after repeated exposure to 3-T MRI brain scans in terms of chromosomal aberrations. They especially study chromosome breaks which are typical of exposure to ionizing radiations. With this aim, they collected **peripheral blood samples in heparin-lithium tubes**, cultured the cells, and prepared them for further analysis (the protocol is described in references).

Surprisingly, and unless I am mistaken, they don't mention the volume of blood they collected for the analysis. After a quick check in the related literature, the collected volume is never mentioned, so I guess it should be standard. Anyway, since the cells are then cultured, not so much blood should be needed. Indeed, the Institute of Genomic Medicine (Rutgers New Jersey Medical School) refers on their webpage dedicated to blood chromosome analysis to "five milliliters of whole blood collected by venipuncture into a green top sodium heparin tube", one indication for testing being the "assessment of chromosome damage in individuals exposed to environmental hazards" (https://research.njms.rutgers.edu/genomics/clinical/blood-chrom.php). This is further supported by the Department of Pathology and Laboratory Medicine from UT Health San Antonio (https://lsom.uthscsa.edu/pathology/reference-labs/clinical-molecular-cytogenetics/chromosome-analysis-blood/).
*** NB: "Blood may be stored at room temperature overnight, refrigerated up to three days, but _**never frozen**_. Blood may also be mailed by overnight courier at ambient temperature. Blood drawn more than five days prior to receipt, or in the wrong tube (such as lithium heparin), is unacceptable." (https://research.njms.rutgers.edu/genomics/clinical/blood-chrom.php) ***

Interestingly, Herate et al. studied exposure to repeated MRI sessions over a span of several months (up to three years). In our case, MRI exposure is much denser and would require the collection of an initial blood sample as soon as possible to be relevant to our study. I agree with Pierre Bellec that such a cytogenetic analysis to our data collection endeavor would be a great addition to our study besides enabling finer investigation of the effects of repeated MRI on chromosomal aberrations, which has so far led to conflicting results.

**Comment by helenelajous** [comment]
@oesteban: Sodium heparin (i.e., dark green tubes instead of light green tubes corresponding to lithium heparin) seems to be the additive we need for chromosomal testing.

**Comment by oesteban** [comment]
Impressive. I will try to get this on Monday

**Comment by celprov** [comment]
Thanks @helenelajous for looking into this!

**Comment by oesteban** [comment]
Thanks much, I'll try to make this happen.

**Comment by helenelajous** [comment]
I've just figured out there is a department of genetic medicine at CHUV, with a lab of constitutional genetics. They look into constitutional cytogenetic anomalies in hereditary diseases, but most importantly, they can run molecular analyses such as fluorescence in situ hybridization (FISH).

I'll call them later today if you're interested @oesteban.
