### ISSUE TITLE
Extraction of phase T1w data

### ISSUE THREAD

**Issue by celprov** [TheAxonLab/hcph-sops#229]
@helenelajous is it correct you suggested we extract not only the magnitude but also the phase information from the T1w scan?

**Comment by helenelajous** [comment]
Yes, that's correct. The idea would be to acquire the "real" data instead of the magnitude image only. But in that case, we cannot display the magnitude image anymore, while this is the HR image we use for fine adjustment of the FOV in the subsequent sequences (DWI, fMRI and T2w). So we first need to be sure that we can properly position the FOV of those sequences on an image without much contrast.

**Comment by helenelajous** [comment]
As an alternative, @oesteban suggested saving the k-space data.
From a practical point-of-view, this would require some time at the end of every session, but probably not a lot more if this is already done for the DWI and fMRI data. If we choose this option, we need to make sure of **saving all the auto-adjustments from the scanner** for subsequent reconstruction of the images.

**Comment by oesteban** [comment]
I'm saving the k-space data including the adjustments from the scanner. We have this for all the 6 sessions (5 successful, one excluded) we have "officially" run thus far.

Considering that writing out complex numbers (it is not exactly magnitude and phase) makes setting the FoV harder, we'll go with the raw data.

I'll close this for now. If someone objects, please reopen and bring up the discussion on why we should get the complex reconstruction instead.

Thanks @celprov and @helenelajous for fostering the open discussion of this :)
