### ISSUE TITLE
Pull *DataLad* data to Sherlock

### ISSUE THREAD

**Issue by celprov** [TheAxonLab/hcph-sops#241]
If we can figure out how to pull the data from *DataLad* to Sherlock, I propose running MRIQC and fMRIPrep on the data each night after being acquired so that I can QA it.

I can follow "live" until session 14, but then I will leave on vacation for one week.

**Comment by oesteban** [comment]
Fully agreed with MRIQC, but we should not do this with fMRIPrep because it will require all the sessions to have been collected, as we state in the RR, for a number of reasons. One fast reason is that we don't have access to the T1w we have not collected yet (obviously), so the anatomical template cannot be created yet.

Let's focus then on the MRIQC pipeline - instead of running it on the cluster, I can have it run overnight on my computer. Can you update the sops at two points:
- the preliminary page (under data-management/), saying how to create a datalad dataset for the derivatives; and
- the mriqc page (under data-management/), saying how to run it and how to save and push the data in the datalad dataset described above.
?

**Comment by celprov** [comment]
Good point about fMRIPrep, I had not thought about the T1 template.

Sounds good for MRIQC. I presume then you solved the problem of your computer being out of memory. Will you go through the MRIQC reports or you want me to do it?

Sent from my T-Mobile 5G Device
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by oesteban** [comment]
Okay, making progress. Data are uploading but at a rate of 6MB/s (see https://github.com/datalad/datalad/issues/7520)

**Comment by oesteban** [comment]
Finally R'synced - can close.
