### ISSUE TITLE
Resting-state were triggered by hand in the early days

### ISSUE THREAD

**Issue by celprov** [TheAxonLab/hcph-sops#271]
Now that I think about it, there were some sessions in the past piloting when we were triggering the resting-state task by hand.

That means that the time of "Keypress : s" in the psychopy log does not exactly correspond to the beginning of the fMRI recording. And this basically mean that we cannot trust the movie onset. 

I think we can do nothing except warn in the dataset that the movie onset for those sessions cannot be trusted.

Also I don't know from when did we fix that issue, and we started triggering the rs using the syncbox, so hard to say up from which piloting session can we trust the movie onset (@esavary do you know when we corrected that problem?). If no one knows, we have to declare all piloting sessions movie onset untrustworthy.

@esavary do you remember if we sometimes triggered by hand the bht or the qct?

**Comment by esavary** [comment]
Hi! I can't pinpoint the exact moment when we stopped manual triggering, but I do know that things started working correctly in May when we added the Biopac. We also faced an issue with manually stopping the task, but we can figure out when that got fixed by looking at when pull request TheAxonLab/HCPh-fMRI-tasks#22 was merged.

**Comment by oesteban** [comment]
After merging #336, this shouldn't be a problem for the events file generation. However, I believe it will be a problem for the physio files because the problem typically was the triggers not being forwarded. Let's close it for now and reopen it (or new issues) if we hit some snag converting some session's physio, psychopy or ET.
